import { grayscale } from "@/shared/config/theme/Colors";
import { StyleSheet } from "react-native";
import type { DefaultTheme } from "styled-components/native";

export const createFriendInviteBottomSheetStyles = (theme: DefaultTheme) => {
	const rem = (value: number) => parseFloat(theme.rem(value));

	return StyleSheet.create({
		container: {
			width: "100%",
			padding: rem(16),
			borderTopLeftRadius: rem(36),
			borderTopRightRadius: rem(36),
			backgroundColor: grayscale.gray950,
			gap: rem(16),
		},
		bottomSheet: {
			zIndex: 1000,
			elevation: 1000,
		},
		header: {
			alignItems: "center",
			alignSelf: "stretch",
			gap: rem(16),
		},
		titleWrapper: {
			alignItems: "center",
			gap: rem(16),
		},
		title: {
			overflow: "hidden",
			color: grayscale.gray100,
			textAlign: "center",
			fontFamily: "Pretendard-SemiBold",
			fontWeight: "600",
			fontSize: 16,
			lineHeight: 20,
			letterSpacing: -0.32,
		},
		contentGroup: {
			flexDirection: "column",
			alignItems: "center",
			alignSelf: "stretch",
			gap: rem(16),
		},
		speechBubbleContainer: {
			position: "relative",
			alignSelf: "stretch",
			alignItems: "center",
		},
		speechBubble: {
			paddingVertical: rem(10),
			paddingHorizontal: rem(16),
			borderRadius: 20,
			backgroundColor: grayscale.gray800,
			maxWidth: "100%",
		},
		speechBubbleText: {
			color: grayscale.gray100,
			fontFamily: "Pretendard-Regular",
			fontSize: 16,
			lineHeight: 24,
			letterSpacing: -0.32,
		},
		speechBubbleArrow: {
			position: "absolute",
			bottom: -rem(13),
			width: rem(23),
			height: rem(23),
		},
		characterWrapper: {
			alignItems: "center",
			justifyContent: "center",
		},
		characterGradient: {
			width: rem(124),
			height: rem(124),
			borderRadius: rem(62),
			alignItems: "center",
			justifyContent: "center",
			shadowColor: "rgba(246, 115, 31, 0.5)",
			shadowOpacity: 1,
			shadowOffset: { width: 0, height: 0 },
			shadowRadius: rem(30),
			elevation: 20,
		},
		characterImage: {
			width: rem(108),
			height: rem(108),
			resizeMode: "contain",
		},
		codeOwnerRow: {
			flexDirection: "row",
			alignItems: "center",
			gap: rem(10),
			alignSelf: "stretch",
		},
		codeOwnerTexts: {
			flexDirection: "row",
			alignItems: "center",
			gap: rem(4),
		},
		friendName: {
			color: grayscale.white,
			fontFamily: "Pretendard-SemiBold",
			fontWeight: "500",
			fontSize: 14,
			lineHeight: 16,
			letterSpacing: -0.28,
		},
		friendCodeLabel: {
			color: grayscale.gray200,
			fontFamily: "Pretendard-SemiBold",
			fontWeight: "500",
			fontSize: 14,
			lineHeight: 16,
			letterSpacing: -0.28,
		},
		codeDisplay: {
			flexDirection: "row",
			alignItems: "center",
			justifyContent: "space-between",
			alignSelf: "stretch",
			paddingTop: rem(8),
			paddingBottom: rem(8),
			paddingRight: rem(8),
			paddingLeft: rem(16),
			borderRadius: rem(20),
			borderWidth: 1,
			borderColor: grayscale.gray700,
			backgroundColor: grayscale.black,
			gap: rem(8),
		},
		codeText: {
			color: grayscale.gray50,
			fontFamily: "Pretendard-Regular",
			fontSize: 16,
			lineHeight: 24,
			letterSpacing: -0.32,
		},
		copyButton: {
			flexDirection: "row",
			alignItems: "center",
			justifyContent: "center",
			paddingVertical: rem(10),
			paddingHorizontal: rem(14),
			borderRadius: 40,
			backgroundColor: grayscale.gray800,
			borderWidth: 1,
			borderColor: "transparent",
			gap: rem(4),
		},
		copyButtonActive: {
			borderColor: grayscale.gray500,
			backgroundColor: grayscale.gray800,
		},
		copyButtonText: {
			color: grayscale.gray200,
			fontFamily: "Pretendard-SemiBold",
			fontWeight: "500",
			fontSize: 16,
			lineHeight: 20,
			letterSpacing: -0.32,
		},
		copyButtonTextActive: {
			color: grayscale.white,
		},
		copyButtonIcon: {
			marginLeft: 0,
		},
		infoText: {
			color: grayscale.gray200,
			textAlign: "center",
			fontFamily: "Pretendard-Regular",
			fontSize: 14,
			lineHeight: 20,
			letterSpacing: -0.28,
			alignSelf: "stretch",
		},
		promptRow: {
			flexDirection: "row",
			alignItems: "center",
			gap: rem(4),
			alignSelf: "stretch",
		},
		promptQuestion: {
			color: grayscale.white,
			fontFamily: "Pretendard-SemiBold",
			fontWeight: "500",
			fontSize: 14,
			lineHeight: 16,
			letterSpacing: -0.28,
		},
		promptAction: {
			color: grayscale.gray200,
			fontFamily: "Pretendard-SemiBold",
			fontWeight: "500",
			fontSize: 14,
			lineHeight: 16,
			letterSpacing: -0.28,
		},
		codeEntryContainer: {
			flexDirection: "row",
			alignItems: "center",
			justifyContent: "space-between",
			alignSelf: "stretch",
			paddingVertical: rem(8),
			paddingRight: rem(8),
			paddingLeft: rem(16),
			borderRadius: 20,
			borderWidth: 1,
			borderColor: grayscale.gray700,
			backgroundColor: grayscale.black,
			gap: rem(8),
		},
		codeEntryInput: {
			flex: 1,
			color: grayscale.gray50,
			fontFamily: "Pretendard-Regular",
			fontSize: 16,
			lineHeight: 24,
			letterSpacing: -0.32,
			paddingVertical: rem(4),
		},
		codeEntryButton: {
			height: rem(44),
			paddingVertical: rem(10),
			paddingHorizontal: rem(14),
			borderRadius: 40,
			backgroundColor: grayscale.gray800,
			alignItems: "center",
			justifyContent: "center",
		},
		codeEntryButtonText: {
			color: grayscale.gray200,
			fontFamily: "Pretendard-SemiBold",
			fontWeight: "500",
			fontSize: 16,
			lineHeight: 20,
			letterSpacing: -0.32,
		},
	});
};

export type FriendInviteBottomSheetStyles = ReturnType<
	typeof createFriendInviteBottomSheetStyles
>;
